### ISSUE TITLE
Set default deployment path to /api/rest, /api/websocket, /admin

### ISSUE THREAD

**Issue by SorJEF** [devicehive/devicehive-java-docker#1]
Set default deployment path for RESTful api to api/rest
For websocket server to api/websocket
For admin console to /admin

**Comment by amososo** [comment]
Hi 
I am trying use devicehive-examples-1.3.0-DeviceExample.jar. But when I try to connect via websockets I get always some exceptions.

My server is configured as follows:
----
RESTful endpoint 	http://[ip]:9080/api/rest
Websocket Client endpoint 	ws://[ip]:9080/api/websocket/client
Websocket Device endpoint 	ws://[ip]:9080/api/websocket/device

Build version: 1.3.1-SNAPSHOT

Build timestamp: 2014-11-20 14:24:52 
----
my call from the console looks like this:
java -jar devicehive-examples-1.3.0-DeviceExample.jar -useSockets -url ws://[ip]:9080/api/websocket

Error:
-->
com.devicehive.client.model.exceptions.HiveException: Error occurred during invoking the target

Any ideas what I am doing wrong?

Thx for your help!

**Comment by demon-xxi** [comment]
In new version of dh it is possible to specify context path 
java -jar -Dserver.context-path=/api devicehive-boot.jar

for this ticket resolution however we will hide admin and devicehive behind nginx or haproxy anyway. so keeping it open.

**Comment by demon-xxi** [comment]
Image 2.0.2 includes the following endpoints by default:
/api - REST API
/api/websocket - WebSockets API
/admin - Admin Console
